import type { CSSProperties } from "react";

type Styles = Record<string, CSSProperties>;

export const styles: Styles = {
  pageBg: {
    minHeight: "100vh",
    background: "#d1d9d3",
    backgroundImage:
      "radial-gradient(at 0% 0%,hsla(145,63%,42%,1) 0px,transparent 50%),radial-gradient(at 100% 100%,rgb(207,36,36) 0px,transparent 50%),radial-gradient(at 0% 100%,hsla(33,85%,55%,0.4) 0px,transparent 50%)",
    padding: "40px 16px",
    fontFamily: "'Prompt', sans-serif",
  },
  mainCard: {
    maxWidth: 680,
    margin: "0 auto",
    background: "#fff",
    borderRadius: 28,
    boxShadow: "0 20px 50px rgba(0,0,0,0.15)",
    overflow: "hidden",
    border: "1px solid rgba(255,255,255,0.8)",
    animation: "fadeUp 0.8s cubic-bezier(0.16,1,0.3,1) forwards",
  },
  headerSection: {
    background: "linear-gradient(135deg,#11261b 0%,#173627 100%)",
    padding: "50px 30px 30px",
    color: "white",
  },
  logoImg: {
    width: "100%",
    height: "auto",
    objectFit: "cover" as const,
    marginBottom: 24,
    padding: 5,
    borderRadius: 25,
    maskImage: "linear-gradient(to bottom,black 80%,transparent 100%)",
    WebkitMaskImage: "linear-gradient(to bottom,black 80%,transparent 100%)",
    display: "block",
  },
  countdownContainer: {
    marginTop: 30,
    paddingTop: 24,
    borderTop: "1px dashed rgba(255,255,255,0.3)",
  },
  countdownTitle: {
    fontFamily: "'Itim', cursive",
    fontSize: "1.3rem",
    color: "#facc15",
    marginBottom: 15,
    textAlign: "center" as const,
  },
  countdownRow: {
    display: "flex",
    justifyContent: "center",
    gap: 10,
    flexWrap: "wrap" as const,
  },
  countdownItem: {
    background: "#fff",
    color: "#173627",
    padding: "12px 10px",
    borderRadius: 16,
    minWidth: 68,
    textAlign: "center" as const,
    boxShadow: "0 4px 15px rgba(0,0,0,0.15)",
    transition: "all 0.3s ease",
    cursor: "default",
  },
  countdownValue: {
    fontSize: "1.8rem",
    fontWeight: 700,
    lineHeight: 1,
    fontFamily: "'Itim', cursive",
  },
  countdownLabel: {
    fontSize: "0.8rem",
    fontWeight: 600,
    marginTop: 6,
    color: "#64748b",
  },
  formSection: {
    padding: "30px 40px 40px",
  },
  row: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap" as const,
    marginBottom: 16,
  },
  label: {
    display: "block",
    fontWeight: 500,
    color: "#2c3e50",
    fontSize: "0.95rem",
    marginBottom: 8,
  },
  input: {
    width: "100%",
    display: "block",
    borderRadius: 16,
    padding: "15px 18px",
    border: "1.5px solid #e2e8f0",
    background: "#f8fafc",
    fontSize: "0.95rem",
    transition: "all 0.3s ease",
    color: "#2c3e50",
  },
  infoCard: {
    background: "#f8fafc",
    borderRadius: 16,
    padding: 20,
    border: "1px solid #e2e8f0",
    marginBottom: 24,
  },
  submitBtn: {
    background: "linear-gradient(135deg,#23611f,#173627)",
    color: "white",
    border: "none",
    borderRadius: 18,
    padding: 18,
    fontWeight: 600,
    fontSize: "1.1rem",
    letterSpacing: "0.5px",
    transition: "all 0.3s ease",
    boxShadow: "0 8px 20px rgba(23,54,39,0.25)",
    fontFamily: "'Prompt', sans-serif",
  },
  footer: {
    background: "transparent",
    color: "#64748b",
    padding: 24,
    textAlign: "center" as const,
    fontSize: "0.85rem",
    borderTop: "1px solid rgba(0,0,0,0.05)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  footerLogo: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    filter: "grayscale(100%)",
    opacity: 0.6,
    verticalAlign: "middle",
  },
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(255,255,255,0.85)",
    backdropFilter: "blur(8px)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column" as const,
  },
  modal: {
    background: "#fff",
    borderRadius: 24,
    padding: "32px 28px",
    maxWidth: 420,
    width: "90vw",
    boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
    maxHeight: "90vh",
    overflowY: "auto" as const,
  },
};
